### ISSUE TITLE
没有issue 反编译asar文件去除electron-vue的waring信息

### ISSUE THREAD

**Issue by simon300000** [w4ctech/discuss#26]
虽然很想评论试试看给process.env来一个ELECTRON_DISABLE_SECURITY_WARNINGS大礼包，但是issue没有，评论加载失败→_→

https://w4ctech.js.org/posts/remove-electron-vue-waring.html

![536194E1-E2FF-40F7-B47B-A6D47291CB9A](https://user-images.githubusercontent.com/12656264/70601329-19605280-1bf2-11ea-8266-f1545ab1fb0e.png)

**Comment by w4ctech** [comment]
> 虽然很想评论试试看给process.env来一个ELECTRON_DISABLE_SECURITY_WARNINGS大礼包，但是issue没有，评论加载失败→_→
> 
> https://w4ctech.js.org/posts/remove-electron-vue-waring.html
> 
> ![536194E1-E2FF-40F7-B47B-A6D47291CB9A](https://user-images.githubusercontent.com/12656264/70601329-19605280-1bf2-11ea-8266-f1545ab1fb0e.png)

thanks
